language: php

php:
  - '7.1'
services:
  - docker

script:
  - docker-compose build
  - docker-compose run tests

deploy:
  - provider: script
    script: auto/deploy.sh production
    on:
      branch: master

