version: '3'

services:

  run:
    container_name: althingi-source-source-run
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    ports:
      - 7070:80
      - 9003:9003
    volumes:
      - ./config/:/var/www/config
      - ./src/:/var/www/src
      - ./tests/:/var/www/tests
      - ./public/:/var/www/public
      - ./bin/:/var/www/bin
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./vendor/:/var/www/vendor
      - ./phpunit.xml.dist/:/var/www/phpunit.xml
    environment:
      - LOG_PATH=php://stdout

      - ENVIRONMENT=development

      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=${ENV_DB_NAME:-althingi}
      - DB_USER=${ENV_DB_USER:-root}
      - DB_PASSWORD=${ENV_DB_PASSWORD:-example}

      - CACHE_TYPE=none

      - BROKER=amqp
      - BROKER_HOST=host.docker.internal
      - BROKER_USER=admin
      - BROKER_PASSWORD=Admin@123

      - DOCUMENT_SERVER=${ENV_DOCUMENT_SERVER:-localhost:8080}
      - DOCUMENT_DEFINITION=${ENV_DOCUMENT_DEFINITION:-/openapi}

      - INDEXER_STALL_TIME=${ENV_INDEXER_STALL_TIME:-150000}
    depends_on:
      - database

  test:
    container_name: althingi-source-source-test
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./composer.json/:/var/www/composer.json
      - ./composer.lock/:/var/www/composer.lock
      - ./config/:/var/www/config
    #   - ./vendor/:/var/www/vendor
      - ./src/:/var/www/src
      - ./public/:/var/www/public
      - ./tests/:/var/www/tests
      - ./bin/:/var/www/bin
      - ./phpcs.xml:/var/www/phpcs.xml
      - ./phpunit.xml.dist:/var/www/phpunit.xml
      - ./auto/wait-for.sh:/var/www/wait-for.sh
    environment:
      - ENVIRONMENT=development

      - LOG_PATH=none

      - DB_HOST=database-test
      - DB_PORT=3306
      - DB_NAME=althingi
      - DB_USER=root
      - DB_PASSWORD=example

      - CACHE_TYPE=none

      - BROKER=none

      - DOCUMENT_SERVER=${ENV_DOCUMENT_SERVER:-localhost:8080}
      - DOCUMENT_DEFINITION=${ENV_DOCUMENT_DEFINITION:-/openapi}

      - INDEXER_STALL_TIME=${ENV_INDEXER_STALL_TIME:-150000}
    depends_on:
      - database-test
    command: bash -c "./wait-for.sh database-test:3306 -t 80 -- echo \"MySQL up\" &&  ./vendor/bin/phpunit && ./vendor/bin/phpcs --standard=./phpcs.xml ./src"

  database:
    container_name: althingi-source-source-db
    image: einarvalur/althingi-source-db:25ee965
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - source-db-volume-development:/var/lib/mysql

  database-test:
      container_name: althingi-source-source-db-test
      image: einarvalur/althingi-source-db:25ee965
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=example

volumes:
    source-db-volume-development:
        external: true
