version: '3'

services:

  # = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
  # TEST
  #
  # Run PHPUnit is a container
  # mostly used for CI but can bes used for local development as well
  # = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
  test:
    container_name: althingi_test_container
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - database
    links:
      - database
    environment:
      - APPLICATION_ENVIRONMENT=development
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=althingi
      - DB_NAME_TEST=althingi
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_SETUP=false
      - CACHE_TYPE=none
      - SEARCH=none
    command: bash -c "/usr/src/vendor/bin/phpunit && /usr/src/vendor/bin/phpcs"

  database:
    container_name: althingi_test_database
    image: mysql:5.6.41
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./auto/db/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=example
