version: '2'
services:
  database:
      image: mysql:5.7
  web:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/module/Althingi
